openapi: 3.0.2
info:
  title: User Preferences API
  description: Topcoder API
  version: 1.0.0
paths:
  '/users/me-preferences':
    get:
      responses:
        '200':
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserPreferences'
          description: Success
      tags:
        - Users
      summary: Get notification preferences for current user.
    patch:
      responses:
        '200':
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserPreferences'
          description: Success
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPreferencesPatch'
        required: true
      summary: Update notification preferences for current user.
components:
  schemas:
    GeneralPreferences:
      type: object
      required:
        - Email.DiscussionComment
        - Email.BookmarkComment
        - Email.Mention
        - Email.ParticipateComment
        - Popup.DiscussionComment
        - Popup.BookmarkComment
        - Popup.Mention
        - Popup.ParticipateComment
      properties:
        Email.DiscussionComment:
          description: Notify me when people comment on my discussions
          type: integer
          minimum: 0
          maximum: 1
        Email.BookmarkComment:
          description: Notify me when people comment on my bookmarked
          type: integer
          minimum: 0
          maximum: 1
        Email.Mention:
          description: Notify me when people mention me
          type: integer
          minimum: 0
          maximum: 1
        Email.ParticipateComment:
          description: Notify me when people comment on discussions I\'ve participated in
          type: integer
          minimum: 0
          maximum: 1
        Popup.DiscussionComment:
          description: Notify me when people comment on my discussions
          type: integer
          minimum: 0
          maximum: 1
        Popup.BookmarkComment:
          description: Notify me when people comment on my bookmarked discussions
          type: integer
          minimum: 0
          maximum: 1
        Popup.Mention:
          description: Notify me when people mention me
          type: integer
          minimum: 0
          maximum: 1
        Popup.ParticipateComment:
          description: Notify me when people comment on discussions I\'ve participated in
          type: integer
          minimum: 0
          maximum: 1
    CategoryPreferences:
      type: object
      required:
        - CategoryID
        - Email.NewDiscussion
        - Email.NewComment
        - Popup.NewDiscussion
        - Popup.NewComment
      properties:
        CategoryID:
          type: integer
        Email.NewDiscussion:
          type: integer
          minimum: 0
          maximum: 2
        Email.NewComment:
          type: integer
          minimum: 0
          maximum: 2
        Popup.NewDiscussion:
          type: integer
          minimum: 0
          maximum: 2
        Popup.NewComment:
          type: integer
          minimum: 0
          maximum: 2
    UserPreferences:
       type: object
       properties:
         GeneralPreferences:
           $ref: '#/components/schemas/GeneralPreferences'
         CategoryPreferences:
           type: array
           items:
             $ref: '#/components/schemas/CategoryPreferences'
       required:
         - GeneralPreferences
         - CategoryPreferences
    UserPreferencesPatch:
      type: object
      properties:
        GeneralPreferences:
           $ref: '#/components/schemas/GeneralPreferences'
        CategoryPreferences:
          type: array
          items:
             $ref: '#/components/schemas/CategoryPreferences'
        required:
          - GeneralPreferences
          - CategoryPreferences