openapi: 3.0.2
info: Vanilla Service API
paths:
  /service/tidewayslog:
    get:
      responses:
        '200':
          content:
            'text/plain':
              schema:
                type: string
          description: Success
      tags:
        - Services
      summary: File.
